spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: notifyOrderEvent
      group-id: cliente
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #"forza" ad adottare i nomi di @Table
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
